source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EventCenter_Example' do
  pod "EventCenter", :path => "../"
end

target 'EventCenter_Tests' do
  pod "EventCenter", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end
